name: build

on:
  push:
    branches:
      - main

jobs:
  build_protobuf:
    uses: bitcompat/base/.github/workflows/build-library.yaml@main
    with:
      name: protobuf
      path: lib/protobuf

  build_unixodbc:
    uses: bitcompat/base/.github/workflows/build-library.yaml@main
    with:
      name: unixodbc
      path: lib/unixodbc

  build_libproj:
    uses: bitcompat/base/.github/workflows/build-library.yaml@main
    with:
      name: libproj
      path: lib/libproj

  build_gdal:
    needs:
      - build_protobuf
      - build_unixodbc
      - build_libproj
    strategy:
      matrix:
        platform:
          - { name: amd64, image: ubuntu-24.04 }
          - { name: arm64, image: ubuntu-24.04-arm }

    name: Build GDAL library - ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.image }}

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/download-artifact@v4
        with:
          name: protobuf-${{ matrix.platform.name }}
          path: lib/gdal/build/protobuf
      - uses: actions/download-artifact@v4
        with:
          name: unixodbc-${{ matrix.platform.name }}
          path: lib/gdal/build/unixodbc
      - uses: actions/download-artifact@v4
        with:
          name: libproj-${{ matrix.platform.name }}
          path: lib/gdal/build/libproj

      - run: |
          mkdir -p lib/gdal/lib
          mv lib/gdal/build/unixodbc/build.tar lib/gdal/lib/unix-odbc.tar
          mv lib/gdal/build/libproj/build.tar lib/gdal/lib/libproj.tar
          mv lib/gdal/build/protobuf/build.tar lib/gdal/lib/protobuf.tar
          cd lib/gdal/lib/
          tar xf unix-odbc.tar
          tar xf libproj.tar
          tar xf protobuf.tar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.platform.name }}
          context: lib/gdal
          tags: gdal-build:latest
          load: true
          cache-from: type=gha,scope=gdal=${{ matrix.platform.name }}
          cache-to: type=gha,mode=max,scope=gdal=${{ matrix.platform.name }}

      - name: Extract compiled library
        run: |
          rm -rf build
          docker create --name lib gdal-build:latest
          docker cp -a lib:/opt/bitnami build
          tar -cf build.tar build/

      - name: Upload built library result
        uses: actions/upload-artifact@v4
        with:
          name: gdal-${{ matrix.platform.name }}
          path: build.tar

  build_amd_image:
    needs: [build_gdal]
    name: Build AMD64 Image - PostgreSQL ${{ matrix.postgresql_version.version }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        postgresql_version:
          - version: '18.0' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
          - version: '17.6' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
          - version: '16.10' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
          - version: '15.14' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
          - version: '14.19' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
          - version: '13.22' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/download-artifact@v4
        with:
          name: gdal-amd64
          path: build/linux/amd64

      - name: Extract built artifacts
        run: |
          pushd build/linux/amd64
          tar xf build.tar
          rm build.tar
          popd

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest

      - name: Build and Push container images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          build-args: |
            RUN_TESTS=0
            SERVER_VERSION=${{ matrix.postgresql_version.version }}
          push: false
          context: .
          cache-from: type=gha,scope=postgresql-${{ matrix.postgresql_version.version }}-amd64
          cache-to: type=gha,mode=max,scope=postgresql-${{ matrix.postgresql_version.version }}-amd64

  build_arm_image:
    needs: [build_gdal]
    name: Build ARM64 Image - PostgreSQL ${{ matrix.postgresql_version.version }}
    runs-on: ubuntu-24.04-arm

    strategy:
      matrix:
        postgresql_version:
          - version: '18.0' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
          - version: '17.6' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
          - version: '16.10' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
          - version: '15.14' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
          - version: '14.19' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
          - version: '13.22' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/download-artifact@v4
        with:
          name: gdal-arm64
          path: build/linux/arm64

      - name: Extract built artifacts
        run: |
          pushd build/linux/arm64
          tar xf build.tar
          rm build.tar
          popd

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest

      - name: Build and Push container images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          build-args: |
            RUN_TESTS=0
            SERVER_VERSION=${{ matrix.postgresql_version.version }}
          push: false
          context: .
          cache-from: type=gha,scope=postgresql-${{ matrix.postgresql_version.version }}-arm64
          cache-to: type=gha,mode=max,scope=postgresql-${{ matrix.postgresql_version.version }}-arm64

  build_package:
    needs: [build_amd_image, build_arm_image]
    name: Build package - PostgreSQL ${{ matrix.postgresql_version.version }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        postgresql_version:
          - version: '18.0' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
            latest: true
          - version: '17.6' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
            latest: false
          - version: '16.10' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
            latest: false
          - version: '15.14' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
            latest: false
          - version: '14.19' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
            latest: false
          - version: '13.22' # renovate: datasource=github-tags depName=postgres/postgres extractVersion=^REL_?(?<version>[\d_]+)$ versioning=loose
            latest: false

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/download-artifact@v4
        with:
          name: gdal-amd64
          path: build/linux/amd64

      - uses: actions/download-artifact@v4
        with:
          name: gdal-arm64
          path: build/linux/arm64

      - name: Extract built artifacts
        run: |
          pushd build/linux/amd64
          tar xf build.tar
          rm build.tar
          popd
          pushd build/linux/arm64
          tar xf build.tar
          rm build.tar
          popd

      - uses: bitcompat/compute-ghcr-revision-action@v1
        id: version-tags
        with:
            version: '${{ matrix.postgresql_version.version }}'
            debian_codename: 'bookworm'
            major_only_tag: 'true'

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        name: Extract docker image metadata
        uses: docker/metadata-action@v5.8.0
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
            public.ecr.aws/bitcompat/${{ github.event.repository.name }}
          tags: |
            ${{ matrix.version.latest && 'latest' || '' }}
            ${{ steps.version-tags.outputs.tags }}

      - name: Build and Push container images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            RUN_TESTS=0
            SERVER_VERSION=${{ matrix.postgresql_version.version }}
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: |-
            type=gha,scope=postgresql-${{ matrix.postgresql_version.version }}-amd64
            type=gha,scope=postgresql-${{ matrix.postgresql_version.version }}-arm64

      - name: Setup CRANE
        uses: imjasonh/setup-crane@v0.4

      - name: Login to ECR Public in CRANE
        run: crane auth login public.ecr.aws -u "${{ steps.login-ecr.outputs.docker_username_public_ecr_aws }}" -p "${{ steps.login-ecr.outputs.docker_password_public_ecr_aws }}"

      - name: Flatten images
        id: flatten_images
        run: |
          set -ex
          DIGEST=""
          while read -r IMG; do
            export OUT=$(crane flatten "$IMG")
            DIGEST=$(echo "$OUT" | awk 'END{print}' | cut -d'@' -f2)
          done <<< $(echo $DOCKER_METADATA_OUTPUT_JSON | jq -r '.tags[]')
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"

      - name: Sign image with a key
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          DIGEST: ${{ steps.flatten_images.outputs.digest }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
